services:
  frontend-dev:
    image: node:lts-alpine
    container_name: frontend-dev-compareit
    command: sh -c "npm install -g npm@latest && npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - compareit-network
    depends_on:
      - backend
      - postgres

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-compareit
    ports:
      - "8080:8080"
    networks:
      - compareit-network
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://compareit_user:compareit_pass@postgres:5432/compareit_db?sslmode=disable
      - JWT_SECRET=your_jwt_secret_here
      - TELEGRAM_BOT_TOKEN=2202117750:AAH9HAbQhXBGlNutYkWKg_vODVwWa2c8LgA
      - TELEGRAM_WEBHOOK_URL=

  postgres:
    image: postgres:13
    container_name: postgres-compareit
    environment:
      POSTGRES_DB: compareit_db
      POSTGRES_USER: compareit_user
      POSTGRES_PASSWORD: compareit_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - compareit-network

volumes:
  postgres_data:

networks:
  compareit-network:
    driver: bridge